services:
  - type: web
    name: invoice-service
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9